import type { Metadata } from "next";

/**
 * override meta data on specic page(s)
 */
export const metadata: Metadata = {
  description: "Generated by nested layout",
  // title: "Next App Auth Pages",

  // a default is required when creating a template
  title: {
    absolute: "va spécifier un chemin absolue vers une ressource", // title.absolute can be used to provide a title that ignores title.template set in parent segments.
    default: "Auth Pages", // title.default can be used to provide a fallback title to child route segments that don't define a title.
    template: "%s | Auth Page", // title.template can be used to add a prefix or a suffix to titles defined in child route segments.
  },
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <h2>GROUP AUTH LAYOUT</h2>

      <h3>Meta Titles</h3>
      <ul className="list-disc list-inside ml-5">
        <li>Meta title max 50-60 chars</li>
        <li>Mot clés</li>
        <li>descriptif et pertinent</li>
        <li>Chaque page doit avoir un titre UNIQUE</li>
        <li>Eviter le diplicata de contenu</li>
        <li>améliore refenrencement</li>
      </ul>
      {children}
    </>
  );
}
