name: Verify PR Source

on:
  pull_request:
    branches:
      - main

jobs:
  verify-source:
    name: "Vérification de la branche source"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source
        id: check-branch
        run: |
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "::error::Les PRs vers main doivent venir uniquement de la branche staging"
            exit 1
          fi
          echo "✅ PR provient correctement de staging"
